# Generated by Django 6.0.6 on 2026-06-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='branch',
        ),
    ]
