# Generated by Django 6.0.6 on 2026-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_invoice_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Flat', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='branch',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
    ]
