# Generated by Django 6.0.6 on 2026-06-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_plan_branchsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_invoices_per_month',
        ),
    ]
