# Generated by Django 6.0.6 on 2026-06-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_plan_max_invoices_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
