# Generated by Django 6.0.6 on 2026-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_branch_owner_name_branch_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='shop_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
