# Generated by Django 6.0.6 on 2026-06-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
