# Generated by Django 6.0.6 on 2026-06-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_sitesettings_login_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.branch'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.branch'),
        ),
    ]
